export const EGYPT_GOVERNORATES = [
  { name: "القاهرة", cost: 50 },
  { name: "الجيزة", cost: 50 },
  { name: "الإسكندرية", cost: 60 },
  { name: "القليوبية", cost: 70 },
  { name: "الدقهلية", cost: 70 },
  { name: "الشرقية", cost: 70 },
  { name: "الغربية", cost: 70 },
  { name: "المنوفية", cost: 70 },
  { name: "البحيرة", cost: 70 },
  { name: "كفر الشيخ", cost: 70 },
  { name: "دمياط", cost: 70 },
  { name: "بورسعيد", cost: 70 },
  { name: "الإسماعيلية", cost: 70 },
  { name: "السويس", cost: 70 },
  { name: "الفيوم", cost: 90 },
  { name: "بني سويف", cost: 90 },
  { name: "المنيا", cost: 90 },
  { name: "أسيوط", cost: 100 },
  { name: "سوهاج", cost: 100 },
  { name: "قنا", cost: 100 },
  { name: "الأقصر", cost: 100 },
  { name: "أسوان", cost: 100 },
  { name: "البحر الأحمر", cost: 120 },
  { name: "الوادي الجديد", cost: 120 },
  { name: "مطروح", cost: 120 },
  { name: "شمال سيناء", cost: 120 },
  { name: "جنوب سيناء", cost: 120 },
];
